### ISSUE TITLE
getline in libc / FreeBSD

### ISSUE THREAD

**Issue by waitman** [rescrv/libtreadstone#4]
treadstone-json-validate.cc:50:23: error: use of undeclared identifier 'getline'
        ssize_t amt = getline(&line, &line_sz, stdin);

needs _WITH_GETLINE defined (see: man getline)

// C
# define _WITH_GETLINE
# include <assert.h>
# include <stdio.h>
# include <stdlib.h>
# include <string.h>

**Comment by rescrv** [comment]
Thank you.  I've fixed this in 73fdf4.
